---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-v3
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx-v3
spec:
  releaseName: nginx
  chart:
    spec:
      chart: nginx
      version: 18.2.5
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 1m
  valuesFrom:
  - kind: ConfigMap
    name: nginx-v3-values
