# Kustomization custom resource to load resource located in the app directory

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 30s
  path: ./infrastructure/docker-desktop
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
